version: "3.7"

services:

  db:
    container_name: db
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_DATABASES=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '5432:5432'
    networks:
      my_api_network:


  test_db:
    container_name: test_db
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_DB=${TEST_POSTGRES_NAME}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_USER=${TEST_POSTGRES_USER}
    networks:
      my_api_network:

  app:
    container_name: app
    build: ./
    command: sh -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0 --port ${API_PORT}"
    volumes:
      - ./:/usr/src/app/
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      my_api_network:
        aliases:
          - my_api_alias
    depends_on:
      - db


networks:
  my_api_network:
    driver: bridge